// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/verification/custom_novel_fix_verification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i8;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:novel_api/novel_api.dart' as _i3;
import 'package:novel_app/core/interfaces/repositories/i_chapter_repository.dart'
    as _i10;
import 'package:novel_app/core/interfaces/repositories/i_novel_repository.dart'
    as _i13;
import 'package:novel_app/models/chapter.dart' as _i11;
import 'package:novel_app/models/novel.dart' as _i14;
import 'package:novel_app/models/reading_anchor.dart' as _i15;
import 'package:novel_app/models/remote_script.dart' as _i4;
import 'package:novel_app/models/search_result.dart' as _i12;
import 'package:novel_app/services/api_service_wrapper.dart' as _i6;
import 'package:novel_app/services/headless_webview_chapter_list_service.dart'
    as _i16;
import 'package:novel_app/services/headless_webview_errors.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupUploadResponse_1 extends _i1.SmartFake
    implements _i3.BackupUploadResponse {
  _FakeBackupUploadResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteScriptPayload_2 extends _i1.SmartFake
    implements _i4.RemoteScriptPayload {
  _FakeRemoteScriptPayload_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteShareResult_3 extends _i1.SmartFake
    implements _i4.RemoteShareResult {
  _FakeRemoteShareResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetchChapterListResult_4 extends _i1.SmartFake
    implements _i5.FetchChapterListResult {
  _FakeFetchChapterListResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceWrapper extends _i1.Mock implements _i6.ApiServiceWrapper {
  MockApiServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  set authHeaderProvider(
          _i7.Future<Map<String, String>> Function()? _authHeaderProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #authHeaderProvider,
          _authHeaderProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unauthorizedRecoveryProvider(
          _i7.Future<Map<String, String>?> Function()?
              _unauthorizedRecoveryProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #unauthorizedRecoveryProvider,
          _unauthorizedRecoveryProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getHost() => (super.noSuchMethod(
        Invocation.method(
          #getHost,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> setConfig({required String? host}) => (super.noSuchMethod(
        Invocation.method(
          #setConfig,
          [],
          {#host: host},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.BackupUploadResponse> uploadBackup({
    required _i8.File? dbFile,
    _i2.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBackup,
          [],
          {
            #dbFile: dbFile,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i7.Future<_i3.BackupUploadResponse>.value(
            _FakeBackupUploadResponse_1(
          this,
          Invocation.method(
            #uploadBackup,
            [],
            {
              #dbFile: dbFile,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i7.Future<_i3.BackupUploadResponse>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getBackupList() => (super.noSuchMethod(
        Invocation.method(
          #getBackupList,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<String> downloadBackup({
    required String? backupId,
    required String? savePath,
    _i2.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadBackup,
          [],
          {
            #backupId: backupId,
            #savePath: savePath,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #downloadBackup,
            [],
            {
              #backupId: backupId,
              #savePath: savePath,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> deleteBackupOnServer({required String? backupId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBackupOnServer,
          [],
          {#backupId: backupId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.RemoteScriptMeta>> searchRemoteScripts(
          {required String? host}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRemoteScripts,
          [],
          {#host: host},
        ),
        returnValue: _i7.Future<List<_i4.RemoteScriptMeta>>.value(
            <_i4.RemoteScriptMeta>[]),
      ) as _i7.Future<List<_i4.RemoteScriptMeta>>);

  @override
  _i7.Future<_i4.RemoteScriptPayload> getRemoteScript(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteScript,
          [remoteId],
        ),
        returnValue: _i7.Future<_i4.RemoteScriptPayload>.value(
            _FakeRemoteScriptPayload_2(
          this,
          Invocation.method(
            #getRemoteScript,
            [remoteId],
          ),
        )),
      ) as _i7.Future<_i4.RemoteScriptPayload>);

  @override
  _i7.Future<_i4.RemoteShareResult> shareScriptToRemote({
    required String? domain,
    required String? displayName,
    required String? chapterListJs,
    required String? chapterContentJs,
    required String? bookshelfJs,
    required String? sampleUrl,
    required String? urlPattern,
    required bool? chapterListOcr,
    required bool? chapterContentOcr,
    required int? preferredMode,
    required String? sha256,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareScriptToRemote,
          [],
          {
            #domain: domain,
            #displayName: displayName,
            #chapterListJs: chapterListJs,
            #chapterContentJs: chapterContentJs,
            #bookshelfJs: bookshelfJs,
            #sampleUrl: sampleUrl,
            #urlPattern: urlPattern,
            #chapterListOcr: chapterListOcr,
            #chapterContentOcr: chapterContentOcr,
            #preferredMode: preferredMode,
            #sha256: sha256,
          },
        ),
        returnValue:
            _i7.Future<_i4.RemoteShareResult>.value(_FakeRemoteShareResult_3(
          this,
          Invocation.method(
            #shareScriptToRemote,
            [],
            {
              #domain: domain,
              #displayName: displayName,
              #chapterListJs: chapterListJs,
              #chapterContentJs: chapterContentJs,
              #bookshelfJs: bookshelfJs,
              #sampleUrl: sampleUrl,
              #urlPattern: urlPattern,
              #chapterListOcr: chapterListOcr,
              #chapterContentOcr: chapterContentOcr,
              #preferredMode: preferredMode,
              #sha256: sha256,
            },
          ),
        )),
      ) as _i7.Future<_i4.RemoteShareResult>);

  @override
  _i7.Future<void> unshareRemoteScript(String? remoteId) => (super.noSuchMethod(
        Invocation.method(
          #unshareRemoteScript,
          [remoteId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.RemoteScriptUpdate>> checkRemoteScriptUpdates(
          {required List<({String remoteId, int version})>? items}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkRemoteScriptUpdates,
          [],
          {#items: items},
        ),
        returnValue: _i7.Future<List<_i4.RemoteScriptUpdate>>.value(
            <_i4.RemoteScriptUpdate>[]),
      ) as _i7.Future<List<_i4.RemoteScriptUpdate>>);
}

/// A class which mocks [IChapterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChapterRepository extends _i1.Mock
    implements _i10.IChapterRepository {
  MockIChapterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> isChapterCached(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isChapterCached,
          [chapterUrl],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> filterUncachedChapters(List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterUncachedChapters,
          [chapterUrls],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<Map<String, bool>> getChaptersCacheStatus(
          List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChaptersCacheStatus,
          [chapterUrls],
        ),
        returnValue: _i7.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i7.Future<Map<String, bool>>);

  @override
  void clearMemoryState() => super.noSuchMethod(
        Invocation.method(
          #clearMemoryState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<String?> getCachedChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapter,
          [chapterUrl],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<List<_i11.Chapter>> getCachedNovelChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovelChapters,
          [novelUrl],
        ),
        returnValue: _i7.Future<List<_i11.Chapter>>.value(<_i11.Chapter>[]),
      ) as _i7.Future<List<_i11.Chapter>>);

  @override
  _i7.Future<int> getCachedChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChaptersCount,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> getTotalChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalChaptersCount,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i12.ChapterSearchResult>> searchInCachedContent(
    String? keyword, {
    String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInCachedContent,
          [keyword],
          {#novelUrl: novelUrl},
        ),
        returnValue: _i7.Future<List<_i12.ChapterSearchResult>>.value(
            <_i12.ChapterSearchResult>[]),
      ) as _i7.Future<List<_i12.ChapterSearchResult>>);
}

/// A class which mocks [INovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockINovelRepository extends _i1.Mock implements _i13.INovelRepository {
  MockINovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i14.Novel>> getNovels() => (super.noSuchMethod(
        Invocation.method(
          #getNovels,
          [],
        ),
        returnValue: _i7.Future<List<_i14.Novel>>.value(<_i14.Novel>[]),
      ) as _i7.Future<List<_i14.Novel>>);

  @override
  _i7.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String?> findExistingBookshelfUrl(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #findExistingBookshelfUrl,
          [novelUrl],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<_i15.ReadingAnchor?> getLastReadAnchor(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastReadAnchor,
          [novelUrl],
        ),
        returnValue: _i7.Future<_i15.ReadingAnchor?>.value(),
      ) as _i7.Future<_i15.ReadingAnchor?>);

  @override
  _i7.Future<int> updateLastReadAnchor(
    String? novelUrl,
    _i15.ReadingAnchor? anchor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadAnchor,
          [
            novelUrl,
            anchor,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<_i14.Novel?> getNovelByUrl(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelByUrl,
          [novelUrl],
        ),
        returnValue: _i7.Future<_i14.Novel?>.value(),
      ) as _i7.Future<_i14.Novel?>);

  @override
  _i7.Future<_i14.Novel?> getNovelById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelById,
          [id],
        ),
        returnValue: _i7.Future<_i14.Novel?>.value(),
      ) as _i7.Future<_i14.Novel?>);

  @override
  _i7.Future<String?> getNovelUrlById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelUrlById,
          [id],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<int> updateBackgroundSettingById(
    int? id,
    String? setting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSettingById,
          [
            id,
            setting,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateCoverMediaIdById(
    int? id,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCoverMediaIdById,
          [
            id,
            mediaId,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
}

/// A class which mocks [HeadlessWebViewChapterListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeadlessWebViewChapterListService extends _i1.Mock
    implements _i16.HeadlessWebViewChapterListService {
  MockHeadlessWebViewChapterListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.FetchChapterListResult> fetchChapterList(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChapterList,
          [novelUrl],
        ),
        returnValue: _i7.Future<_i5.FetchChapterListResult>.value(
            _FakeFetchChapterListResult_4(
          this,
          Invocation.method(
            #fetchChapterList,
            [novelUrl],
          ),
        )),
      ) as _i7.Future<_i5.FetchChapterListResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
