// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/services/agent_launcher/contextual_agent_launcher_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:novel_app/core/providers/agent_chat_state.dart' as _i3;
import 'package:novel_app/core/providers/current_novel_provider.dart' as _i11;
import 'package:novel_app/core/providers/scenario_session.dart' as _i2;
import 'package:novel_app/core/providers/scenario_sessions_provider.dart'
    as _i4;
import 'package:novel_app/services/novel_agent/agent_scenario.dart' as _i9;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScenarioSession_0 extends _i1.SmartFake
    implements _i2.ScenarioSession {
  _FakeScenarioSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAgentChatState_1 extends _i1.SmartFake
    implements _i3.AgentChatState {
  _FakeAgentChatState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScenarioSessionsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockScenarioSessionsNotifier extends _i1.Mock
    implements _i4.ScenarioSessionsNotifier {
  @override
  List<String> get activeSessionIds => (super.noSuchMethod(
        Invocation.getter(#activeSessionIds),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Stream<Map<String, _i3.AgentChatState>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<Map<String, _i3.AgentChatState>>.empty(),
        returnValueForMissingStub:
            _i5.Stream<Map<String, _i3.AgentChatState>>.empty(),
      ) as _i5.Stream<Map<String, _i3.AgentChatState>>);

  @override
  Map<String, _i3.AgentChatState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: <String, _i3.AgentChatState>{},
        returnValueForMissingStub: <String, _i3.AgentChatState>{},
      ) as Map<String, _i3.AgentChatState>);

  @override
  Map<String, _i3.AgentChatState> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: <String, _i3.AgentChatState>{},
        returnValueForMissingStub: <String, _i3.AgentChatState>{},
      ) as Map<String, _i3.AgentChatState>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set onError(_i6.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(Map<String, _i3.AgentChatState>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ScenarioSession get(String? scenarioId) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [scenarioId],
        ),
        returnValue: _FakeScenarioSession_0(
          this,
          Invocation.method(
            #get,
            [scenarioId],
          ),
        ),
        returnValueForMissingStub: _FakeScenarioSession_0(
          this,
          Invocation.method(
            #get,
            [scenarioId],
          ),
        ),
      ) as _i2.ScenarioSession);

  @override
  _i5.Future<void> switchSession(
    String? scenarioId,
    int? newSessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchSession,
          [
            scenarioId,
            newSessionId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startNewSession(String? scenarioId) => (super.noSuchMethod(
        Invocation.method(
          #startNewSession,
          [scenarioId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i2.ScenarioSession? getIfExists(String? scenarioId) => (super.noSuchMethod(
        Invocation.method(
          #getIfExists,
          [scenarioId],
        ),
        returnValueForMissingStub: null,
      ) as _i2.ScenarioSession?);

  @override
  bool hasSession(String? scenarioId) => (super.noSuchMethod(
        Invocation.method(
          #hasSession,
          [scenarioId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isRunning(String? scenarioId) => (super.noSuchMethod(
        Invocation.method(
          #isRunning,
          [scenarioId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void disposeSession(String? scenarioId) => super.noSuchMethod(
        Invocation.method(
          #disposeSession,
          [scenarioId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    Map<String, _i3.AgentChatState>? old,
    Map<String, _i3.AgentChatState>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.RemoveListener addListener(
    _i7.Listener<Map<String, _i3.AgentChatState>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i6.RemoveListener);
}

/// A class which mocks [ScenarioSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockScenarioSession extends _i1.Mock implements _i2.ScenarioSession {
  @override
  String get scenarioId => (super.noSuchMethod(
        Invocation.getter(#scenarioId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#scenarioId),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#scenarioId),
        ),
      ) as String);

  @override
  List<_i9.ChatMessage> get agentMessages => (super.noSuchMethod(
        Invocation.getter(#agentMessages),
        returnValue: <_i9.ChatMessage>[],
        returnValueForMissingStub: <_i9.ChatMessage>[],
      ) as List<_i9.ChatMessage>);

  @override
  _i3.AgentChatState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAgentChatState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAgentChatState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AgentChatState);

  @override
  bool get isRunning => (super.noSuchMethod(
        Invocation.getter(#isRunning),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.SessionLifecycle get lifecycle => (super.noSuchMethod(
        Invocation.getter(#lifecycle),
        returnValue: _i2.SessionLifecycle.fresh,
        returnValueForMissingStub: _i2.SessionLifecycle.fresh,
      ) as _i2.SessionLifecycle);

  @override
  _i5.Future<void> adoptSession(int? newSessionId) => (super.noSuchMethod(
        Invocation.method(
          #adoptSession,
          [newSessionId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> hydrateIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #hydrateIfNeeded,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> hydrateFromRecentIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #hydrateFromRecentIfNeeded,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setOnStateChanged(_i10.VoidCallback? callback) => super.noSuchMethod(
        Invocation.method(
          #setOnStateChanged,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> sendMessage({
    required String? content,
    List<String>? imageMediaIds = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #content: content,
            #imageMediaIds: imageMediaIds,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> retryLastRound() => (super.noSuchMethod(
        Invocation.method(
          #retryLastRound,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> retryToolCall(String? toolCallId) => (super.noSuchMethod(
        Invocation.method(
          #retryToolCall,
          [toolCallId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i11.CurrentNovel?> selectNovel(int? novelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectNovel,
          [novelId],
        ),
        returnValue: _i5.Future<_i11.CurrentNovel?>.value(),
        returnValueForMissingStub: _i5.Future<_i11.CurrentNovel?>.value(),
      ) as _i5.Future<_i11.CurrentNovel?>);

  @override
  _i5.Future<void> clearConversation() => (super.noSuchMethod(
        Invocation.method(
          #clearConversation,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> rollbackToMessage(
    int? index, {
    required void Function(String)? contentCallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rollbackToMessage,
          [index],
          {#contentCallback: contentCallback},
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
