// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/screens/text_game/text_game_play_choices_layout_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/screens/text_game/game_transcript_projector.dart'
    as _i5;
import 'package:novel_app/screens/text_game/text_game_play_controller.dart'
    as _i2;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextGamePlayState_0 extends _i1.SmartFake
    implements _i2.TextGamePlayState {
  _FakeTextGamePlayState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TextGamePlayController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextGamePlayController extends _i1.Mock
    implements _i2.TextGamePlayController {
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Stream<_i2.TextGamePlayState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.TextGamePlayState>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.TextGamePlayState>.empty(),
      ) as _i3.Stream<_i2.TextGamePlayState>);

  @override
  _i2.TextGamePlayState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTextGamePlayState_0(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeTextGamePlayState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.TextGamePlayState);

  @override
  _i2.TextGamePlayState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeTextGamePlayState_0(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeTextGamePlayState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.TextGamePlayState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(_i2.TextGamePlayState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> restartGame() => (super.noSuchMethod(
        Invocation.method(
          #restartGame,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendInput(String? text) => (super.noSuchMethod(
        Invocation.method(
          #sendInput,
          [text],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendChoice(_i5.GameChoice? choice) => (super.noSuchMethod(
        Invocation.method(
          #sendChoice,
          [choice],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> rollbackToChoices(_i5.GameChoices? segment) =>
      (super.noSuchMethod(
        Invocation.method(
          #rollbackToChoices,
          [segment],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> startGame() => (super.noSuchMethod(
        Invocation.method(
          #startGame,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelTurn() => (super.noSuchMethod(
        Invocation.method(
          #cancelTurn,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i2.TextGamePlayState? old,
    _i2.TextGamePlayState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.RemoveListener addListener(
    _i6.Listener<_i2.TextGamePlayState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i4.RemoveListener);
}
