// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/widgets/webview_add_novel_fab_orchestration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/services/agent_launcher/agent_launch_request.dart'
    as _i5;
import 'package:novel_app/services/agent_launcher/contextual_agent_launcher.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContextualAgentLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextualAgentLauncher extends _i1.Mock
    implements _i2.ContextualAgentLauncher {
  @override
  _i3.Future<void> launch(
    _i4.BuildContext? context,
    _i5.AgentLaunchRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #launch,
          [
            context,
            request,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
