// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/services/save_script_tool_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:novel_app/models/site_script.dart' as _i6;
import 'package:novel_app/repositories/site_script_repository.dart' as _i5;
import 'package:novel_app/services/ocr_restore_service.dart' as _i4;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOcrRestoreResult_2 extends _i1.SmartFake
    implements _i4.OcrRestoreResult {
  _FakeOcrRestoreResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SiteScriptRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSiteScriptRepository extends _i1.Mock
    implements _i5.SiteScriptRepository {
  MockSiteScriptRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i3.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i3.Future<_i2.Database>);

  @override
  bool get isWebPlatform => (super.noSuchMethod(
        Invocation.getter(#isWebPlatform),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<List<_i6.SiteScript>> getAll({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i6.SiteScript>>.value(<_i6.SiteScript>[]),
      ) as _i3.Future<List<_i6.SiteScript>>);

  @override
  _i3.Future<_i6.SiteScript?> getByDomain(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDomain,
          [domain],
        ),
        returnValue: _i3.Future<_i6.SiteScript?>.value(),
      ) as _i3.Future<_i6.SiteScript?>);

  @override
  _i3.Future<_i6.SiteScript?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i6.SiteScript?>.value(),
      ) as _i3.Future<_i6.SiteScript?>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteByDomain(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #deleteByDomain,
          [domain],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setVerified(
    String? id,
    bool? verified,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVerified,
          [
            id,
            verified,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markUsed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markUsed,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<({String id, bool isInsert})> upsertByDomain({
    required String? domain,
    required String? chapterListJs,
    required String? chapterContentJs,
    String? urlPattern = '',
    String? sampleUrl = '',
    bool? chapterListOcr = false,
    bool? chapterContentOcr = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertByDomain,
          [],
          {
            #domain: domain,
            #chapterListJs: chapterListJs,
            #chapterContentJs: chapterContentJs,
            #urlPattern: urlPattern,
            #sampleUrl: sampleUrl,
            #chapterListOcr: chapterListOcr,
            #chapterContentOcr: chapterContentOcr,
          },
        ),
        returnValue: _i3.Future<({String id, bool isInsert})>.value((
          id: _i7.dummyValue<String>(
            this,
            Invocation.method(
              #upsertByDomain,
              [],
              {
                #domain: domain,
                #chapterListJs: chapterListJs,
                #chapterContentJs: chapterContentJs,
                #urlPattern: urlPattern,
                #sampleUrl: sampleUrl,
                #chapterListOcr: chapterListOcr,
                #chapterContentOcr: chapterContentOcr,
              },
            ),
          ),
          isInsert: false
        )),
      ) as _i3.Future<({String id, bool isInsert})>);

  @override
  _i3.Future<({String? id, String? reason, bool success})> updateScriptPart({
    required String? domain,
    required String? scriptType,
    required String? scriptJs,
    required bool? ocr,
    String? testUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScriptPart,
          [],
          {
            #domain: domain,
            #scriptType: scriptType,
            #scriptJs: scriptJs,
            #ocr: ocr,
            #testUrl: testUrl,
          },
        ),
        returnValue:
            _i3.Future<({String? id, String? reason, bool success})>.value(
                (id: null, reason: null, success: false)),
      ) as _i3.Future<({String? id, String? reason, bool success})>);

  @override
  _i3.Future<T> guard<T>(
    String? opTag,
    _i3.Future<T> Function()? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #guard,
          [
            opTag,
            body,
          ],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #guard,
                  [
                    opTag,
                    body,
                  ],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #guard,
                [
                  opTag,
                  body,
                ],
              ),
            ),
      ) as _i3.Future<T>);
}

/// A class which mocks [OcrRestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOcrRestoreService extends _i1.Mock implements _i4.OcrRestoreService {
  MockOcrRestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.OcrRestoreResult> restorePuaInText(
    String? text,
    String? fontFamily,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restorePuaInText,
          [
            text,
            fontFamily,
          ],
        ),
        returnValue:
            _i3.Future<_i4.OcrRestoreResult>.value(_FakeOcrRestoreResult_2(
          this,
          Invocation.method(
            #restorePuaInText,
            [
              text,
              fontFamily,
            ],
          ),
        )),
      ) as _i3.Future<_i4.OcrRestoreResult>);

  @override
  _i3.Future<bool> verifyFontFamily(String? fontFamily) => (super.noSuchMethod(
        Invocation.method(
          #verifyFontFamily,
          [fontFamily],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  double readableRatio(String? text) => (super.noSuchMethod(
        Invocation.method(
          #readableRatio,
          [text],
        ),
        returnValue: 0.0,
      ) as double);
}
