// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/services/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i7;
import 'dart:typed_data' as _i9;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:novel_api/novel_api.dart' as _i3;
import 'package:novel_app/models/remote_script.dart' as _i4;
import 'package:novel_app/services/api_service_wrapper.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupUploadResponse_1 extends _i1.SmartFake
    implements _i3.BackupUploadResponse {
  _FakeBackupUploadResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteScriptPayload_2 extends _i1.SmartFake
    implements _i4.RemoteScriptPayload {
  _FakeRemoteScriptPayload_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteShareResult_3 extends _i1.SmartFake
    implements _i4.RemoteShareResult {
  _FakeRemoteShareResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceWrapper extends _i1.Mock implements _i5.ApiServiceWrapper {
  MockApiServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  set authHeaderProvider(
          _i6.Future<Map<String, String>> Function()? _authHeaderProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #authHeaderProvider,
          _authHeaderProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unauthorizedRecoveryProvider(
          _i6.Future<Map<String, String>?> Function()?
              _unauthorizedRecoveryProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #unauthorizedRecoveryProvider,
          _unauthorizedRecoveryProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getHost() => (super.noSuchMethod(
        Invocation.method(
          #getHost,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> setConfig({required String? host}) => (super.noSuchMethod(
        Invocation.method(
          #setConfig,
          [],
          {#host: host},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i3.BackupUploadResponse> uploadBackup({
    required _i7.File? dbFile,
    _i2.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBackup,
          [],
          {
            #dbFile: dbFile,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i6.Future<_i3.BackupUploadResponse>.value(
            _FakeBackupUploadResponse_1(
          this,
          Invocation.method(
            #uploadBackup,
            [],
            {
              #dbFile: dbFile,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i6.Future<_i3.BackupUploadResponse>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getBackupList() => (super.noSuchMethod(
        Invocation.method(
          #getBackupList,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<String> downloadBackup({
    required String? backupId,
    required String? savePath,
    _i2.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadBackup,
          [],
          {
            #backupId: backupId,
            #savePath: savePath,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #downloadBackup,
            [],
            {
              #backupId: backupId,
              #savePath: savePath,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> deleteBackupOnServer({required String? backupId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBackupOnServer,
          [],
          {#backupId: backupId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getText2ImgModels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getText2ImgModels,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<String> submitText2ImgTask({
    required String? prompt,
    String? modelName,
    String? negativePrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitText2ImgTask,
          [],
          {
            #prompt: prompt,
            #modelName: modelName,
            #negativePrompt: negativePrompt,
          },
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #submitText2ImgTask,
            [],
            {
              #prompt: prompt,
              #modelName: modelName,
              #negativePrompt: negativePrompt,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<(_i9.Uint8List?, int)> fetchText2ImgImage(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchText2ImgImage,
          [taskId],
        ),
        returnValue: _i6.Future<(_i9.Uint8List?, int)>.value((null, 0)),
      ) as _i6.Future<(_i9.Uint8List?, int)>);

  @override
  _i6.Future<String> submitImageToVideoTask({
    required String? prompt,
    required _i9.Uint8List? imageBytes,
    required String? imageFilename,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitImageToVideoTask,
          [],
          {
            #prompt: prompt,
            #imageBytes: imageBytes,
            #imageFilename: imageFilename,
            #modelName: modelName,
          },
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #submitImageToVideoTask,
            [],
            {
              #prompt: prompt,
              #imageBytes: imageBytes,
              #imageFilename: imageFilename,
              #modelName: modelName,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<(_i9.Uint8List?, int)> fetchImageToVideoVideo(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchImageToVideoVideo,
          [taskId],
        ),
        returnValue: _i6.Future<(_i9.Uint8List?, int)>.value((null, 0)),
      ) as _i6.Future<(_i9.Uint8List?, int)>);

  @override
  _i6.Future<List<_i4.RemoteScriptMeta>> searchRemoteScripts(
          {required String? host}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRemoteScripts,
          [],
          {#host: host},
        ),
        returnValue: _i6.Future<List<_i4.RemoteScriptMeta>>.value(
            <_i4.RemoteScriptMeta>[]),
      ) as _i6.Future<List<_i4.RemoteScriptMeta>>);

  @override
  _i6.Future<_i4.RemoteScriptPayload> getRemoteScript(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteScript,
          [remoteId],
        ),
        returnValue: _i6.Future<_i4.RemoteScriptPayload>.value(
            _FakeRemoteScriptPayload_2(
          this,
          Invocation.method(
            #getRemoteScript,
            [remoteId],
          ),
        )),
      ) as _i6.Future<_i4.RemoteScriptPayload>);

  @override
  _i6.Future<_i4.RemoteShareResult> shareScriptToRemote({
    required String? domain,
    required String? displayName,
    required String? chapterListJs,
    required String? chapterContentJs,
    required String? bookshelfJs,
    required String? sampleUrl,
    required String? urlPattern,
    required bool? chapterListOcr,
    required bool? chapterContentOcr,
    required int? preferredMode,
    required String? sha256,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareScriptToRemote,
          [],
          {
            #domain: domain,
            #displayName: displayName,
            #chapterListJs: chapterListJs,
            #chapterContentJs: chapterContentJs,
            #bookshelfJs: bookshelfJs,
            #sampleUrl: sampleUrl,
            #urlPattern: urlPattern,
            #chapterListOcr: chapterListOcr,
            #chapterContentOcr: chapterContentOcr,
            #preferredMode: preferredMode,
            #sha256: sha256,
          },
        ),
        returnValue:
            _i6.Future<_i4.RemoteShareResult>.value(_FakeRemoteShareResult_3(
          this,
          Invocation.method(
            #shareScriptToRemote,
            [],
            {
              #domain: domain,
              #displayName: displayName,
              #chapterListJs: chapterListJs,
              #chapterContentJs: chapterContentJs,
              #bookshelfJs: bookshelfJs,
              #sampleUrl: sampleUrl,
              #urlPattern: urlPattern,
              #chapterListOcr: chapterListOcr,
              #chapterContentOcr: chapterContentOcr,
              #preferredMode: preferredMode,
              #sha256: sha256,
            },
          ),
        )),
      ) as _i6.Future<_i4.RemoteShareResult>);

  @override
  _i6.Future<void> unshareRemoteScript(String? remoteId) => (super.noSuchMethod(
        Invocation.method(
          #unshareRemoteScript,
          [remoteId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.RemoteScriptUpdate>> checkRemoteScriptUpdates(
          {required List<({String remoteId, int version})>? items}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkRemoteScriptUpdates,
          [],
          {#items: items},
        ),
        returnValue: _i6.Future<List<_i4.RemoteScriptUpdate>>.value(
            <_i4.RemoteScriptUpdate>[]),
      ) as _i6.Future<List<_i4.RemoteScriptUpdate>>);
}
