// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/services/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/models/remote_script.dart' as _i3;
import 'package:novel_app/services/api_service_wrapper.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteScriptPayload_1 extends _i1.SmartFake
    implements _i3.RemoteScriptPayload {
  _FakeRemoteScriptPayload_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteShareResult_2 extends _i1.SmartFake
    implements _i3.RemoteShareResult {
  _FakeRemoteShareResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceWrapper extends _i1.Mock implements _i4.ApiServiceWrapper {
  MockApiServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  set authHeaderProvider(
          _i5.Future<Map<String, String>> Function()? _authHeaderProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #authHeaderProvider,
          _authHeaderProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unauthorizedRecoveryProvider(
          _i5.Future<Map<String, String>?> Function()?
              _unauthorizedRecoveryProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #unauthorizedRecoveryProvider,
          _unauthorizedRecoveryProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> init({String? baseUrl}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#baseUrl: baseUrl},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.RemoteScriptMeta>> searchRemoteScripts(
          {required String? host}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRemoteScripts,
          [],
          {#host: host},
        ),
        returnValue: _i5.Future<List<_i3.RemoteScriptMeta>>.value(
            <_i3.RemoteScriptMeta>[]),
      ) as _i5.Future<List<_i3.RemoteScriptMeta>>);

  @override
  _i5.Future<_i3.RemoteScriptPayload> getRemoteScript(String? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteScript,
          [remoteId],
        ),
        returnValue: _i5.Future<_i3.RemoteScriptPayload>.value(
            _FakeRemoteScriptPayload_1(
          this,
          Invocation.method(
            #getRemoteScript,
            [remoteId],
          ),
        )),
      ) as _i5.Future<_i3.RemoteScriptPayload>);

  @override
  _i5.Future<_i3.RemoteShareResult> shareScriptToRemote({
    required String? domain,
    required String? displayName,
    required String? chapterListJs,
    required String? chapterContentJs,
    required String? bookshelfJs,
    required String? sampleUrl,
    required String? urlPattern,
    required bool? chapterListOcr,
    required bool? chapterContentOcr,
    required int? preferredMode,
    required String? sha256,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareScriptToRemote,
          [],
          {
            #domain: domain,
            #displayName: displayName,
            #chapterListJs: chapterListJs,
            #chapterContentJs: chapterContentJs,
            #bookshelfJs: bookshelfJs,
            #sampleUrl: sampleUrl,
            #urlPattern: urlPattern,
            #chapterListOcr: chapterListOcr,
            #chapterContentOcr: chapterContentOcr,
            #preferredMode: preferredMode,
            #sha256: sha256,
          },
        ),
        returnValue:
            _i5.Future<_i3.RemoteShareResult>.value(_FakeRemoteShareResult_2(
          this,
          Invocation.method(
            #shareScriptToRemote,
            [],
            {
              #domain: domain,
              #displayName: displayName,
              #chapterListJs: chapterListJs,
              #chapterContentJs: chapterContentJs,
              #bookshelfJs: bookshelfJs,
              #sampleUrl: sampleUrl,
              #urlPattern: urlPattern,
              #chapterListOcr: chapterListOcr,
              #chapterContentOcr: chapterContentOcr,
              #preferredMode: preferredMode,
              #sha256: sha256,
            },
          ),
        )),
      ) as _i5.Future<_i3.RemoteShareResult>);

  @override
  _i5.Future<void> unshareRemoteScript(String? remoteId) => (super.noSuchMethod(
        Invocation.method(
          #unshareRemoteScript,
          [remoteId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.RemoteScriptUpdate>> checkRemoteScriptUpdates(
          {required List<({String remoteId, int version})>? items}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkRemoteScriptUpdates,
          [],
          {#items: items},
        ),
        returnValue: _i5.Future<List<_i3.RemoteScriptUpdate>>.value(
            <_i3.RemoteScriptUpdate>[]),
      ) as _i5.Future<List<_i3.RemoteScriptUpdate>>);
}
