"""remove_video_fields_from_image_tables

Revision ID: 1cf2c108acc1
Revises: bb9801edb8c8
Create Date: 2025-12-16 13:28:54.948810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cf2c108acc1'
down_revision = 'bb9801edb8c8'
branch_labels = None
depends_on = None


def _has_table(name: str) -> bool:
    """守卫：遗留漂移操作仅对真实存在旧表的存量库执行。

    全新数据库（从未有过爬虫/缓存时代的表）直接跳过，
    使 `alembic upgrade head` 可从零跑通（2026-09-06 修复）。
    """
    from sqlalchemy import inspect
    return inspect(op.get_bind()).has_table(name)


def upgrade() -> None:
    if not _has_table('role_image_gallery'):
        # 全新库：目标遗留表从未存在，跳过本迁移的漂移操作
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_image_gallery', 'video_status')
    op.drop_column('role_image_gallery', 'video_filename')
    op.drop_column('role_image_gallery', 'video_prompt')
    op.drop_column('role_image_gallery', 'video_created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_image_gallery', sa.Column('video_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='视频创建时间'))
    op.add_column('role_image_gallery', sa.Column('video_prompt', sa.TEXT(), autoincrement=False, nullable=True, comment='视频生成提示词'))
    op.add_column('role_image_gallery', sa.Column('video_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='生成的视频文件名'))
    op.add_column('role_image_gallery', sa.Column('video_status', sa.VARCHAR(length=20), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False, comment='视频生成状态: none/pending/running/completed/failed'))
    # ### end Alembic commands ###