"""Allow task_id to be nullable for individual chapters

Revision ID: 69a1dfa2484c
Revises: e7b3ba19a7f3
Create Date: 2025-12-17 16:01:58.987216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a1dfa2484c'
down_revision = 'e7b3ba19a7f3'
branch_labels = None
depends_on = None


def _has_table(name: str) -> bool:
    """守卫：遗留漂移操作仅对真实存在旧表的存量库执行。

    全新数据库（从未有过爬虫/缓存时代的表）直接跳过，
    使 `alembic upgrade head` 可从零跑通（2026-09-06 修复）。
    """
    from sqlalchemy import inspect
    return inspect(op.get_bind()).has_table(name)


def upgrade() -> None:
    if not _has_table('novel_chapters_cache'):
        # 全新库：目标遗留表从未存在，跳过本迁移的漂移操作
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('novel_chapters_cache', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_card_tasks', 'user_input',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='用户要求',
               existing_server_default=sa.text("'生成人物卡'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_card_tasks', 'user_input',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='用户要求',
               existing_server_default=sa.text("'生成人物卡'::text"))
    op.alter_column('novel_chapters_cache', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###