// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/controllers/chapter_list/chapter_action_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/core/interfaces/repositories/i_chapter_repository.dart'
    as _i2;
import 'package:novel_app/models/chapter.dart' as _i4;
import 'package:novel_app/models/search_result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IChapterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChapterRepository extends _i1.Mock
    implements _i2.IChapterRepository {
  MockIChapterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isChapterCached(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isChapterCached,
          [chapterUrl],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> filterUncachedChapters(List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterUncachedChapters,
          [chapterUrls],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, bool>> getChaptersCacheStatus(
          List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChaptersCacheStatus,
          [chapterUrls],
        ),
        returnValue: _i3.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i3.Future<Map<String, bool>>);

  @override
  void clearMemoryState() => super.noSuchMethod(
        Invocation.method(
          #clearMemoryState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<int> cacheChapter(
    String? novelUrl,
    _i4.Chapter? chapter,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheChapter,
          [
            novelUrl,
            chapter,
            content,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateChapterContent(
    String? chapterUrl,
    String? content, {
    String? source = 'edit',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContent,
          [
            chapterUrl,
            content,
          ],
          {#source: source},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteChapterCache(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteChapterCache,
          [chapterUrl],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String?> getCachedChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapter,
          [chapterUrl],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<List<_i4.Chapter>> getCachedChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapters,
          [novelUrl],
        ),
        returnValue: _i3.Future<List<_i4.Chapter>>.value(<_i4.Chapter>[]),
      ) as _i3.Future<List<_i4.Chapter>>);

  @override
  _i3.Future<int> deleteCachedChapters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedChapters,
          [novelUrl],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> cacheNovelChapters(
    String? novelUrl,
    List<_i4.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNovelChapters,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Chapter>> getCachedNovelChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovelChapters,
          [novelUrl],
        ),
        returnValue: _i3.Future<List<_i4.Chapter>>.value(<_i4.Chapter>[]),
      ) as _i3.Future<List<_i4.Chapter>>);

  @override
  _i3.Future<int> createCustomChapter(
    String? novelUrl,
    String? title,
    String? content, [
    int? index,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomChapter,
          [
            novelUrl,
            title,
            content,
            index,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateCustomChapter(
    String? chapterUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomChapter,
          [
            chapterUrl,
            title,
            content,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCustomChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomChapter,
          [chapterUrl],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> shiftChapterIndicesFrom(
    String? novelUrl,
    int? fromIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shiftChapterIndicesFrom,
          [
            novelUrl,
            fromIndex,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markChapterAsRead(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsRead,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getCachedChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChaptersCount,
          [novelUrl],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalChaptersCount,
          [novelUrl],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateChaptersOrder(
    String? novelUrl,
    List<_i4.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChaptersOrder,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.ChapterSearchResult>> searchInCachedContent(
    String? keyword, {
    String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInCachedContent,
          [keyword],
          {#novelUrl: novelUrl},
        ),
        returnValue: _i3.Future<List<_i5.ChapterSearchResult>>.value(
            <_i5.ChapterSearchResult>[]),
      ) as _i3.Future<List<_i5.ChapterSearchResult>>);

  @override
  _i3.Future<_i4.Chapter?> getChapterById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChapterById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Chapter?>.value(),
      ) as _i3.Future<_i4.Chapter?>);

  @override
  _i3.Future<String?> getChapterUrlById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChapterUrlById,
          [id],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<bool> chapterExistsById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #chapterExistsById,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> updateChapterContentById(
    int? id,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContentById,
          [
            id,
            content,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int?> getChapterIdByUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #getChapterIdByUrl,
          [url],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);
}
